import { Delivery } from '../types/delivery';
import { RawGPSPoint } from '../types/evidence';

export interface DemoScenarioPreset {
  id: 'SCENARIO_A' | 'SCENARIO_B' | 'SCENARIO_C' | 'SCENARIO_D';
  title: string;
  subtitle: string;
  tag: string;
  expectedDecision: 'VERIFIED' | 'REJECTED' | 'REVIEW';
  targetDeliveryId: string;
  simulatedGps: {
    latitude: number;
    longitude: number;
    accuracy: number;
    distanceMeters: number;
  };
  dwellSeconds: number;
  callAttempted: boolean;
  callDurationSeconds: number;
  videoConsentStatus: 'granted' | 'not_requested' | 'timed_out' | 'denied';
  anomalyFlags: string[];
  description: string;
}

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'DEL-1001',
    trackingNumber: 'SBT-BLR-882190',
    customer: {
      id: 'CUST-401',
      name: 'Vishnu Bhargav',
      phone: '+91 90191 44983',
      preferredLanguage: 'English / Kannada',
    },
    address: {
      street: 'Tower 4, Flat 902, Sobha Silicon Oasis',
      unitOrFlat: 'T4-902',
      landmark: 'Near Hosa Road Junction',
      city: 'Bengaluru',
      postalCode: '560100',
      latitude: 12.8715,
      longitude: 77.6534,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Electronics — Sony Wireless ANC Headphones (High Value)',
    estimatedDeliveryWindow: '11:00 AM - 12:00 PM',
    status: 'IN_TRANSIT',
    createdAt: '2026-09-18T09:30:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Gate passcode: #4490 (Customer requested gate verification)',
  },
  {
    id: 'DEL-1002',
    trackingNumber: 'SBT-BLR-882191',
    customer: {
      id: 'CUST-402',
      name: 'Rahul Varma',
      phone: '+91 97412 88712',
    },
    address: {
      street: '12th Main Road, HAL 2nd Stage, Indiranagar',
      unitOrFlat: '#542',
      landmark: 'Behind Corner House',
      city: 'Bengaluru',
      postalCode: '560038',
      latitude: 12.9719,
      longitude: 77.6412,
      residenceCategory: 'individual_house',
    },
    packageDescription: 'Apparel & Footwear — Nike Running Shoes',
    estimatedDeliveryWindow: '12:15 PM - 01:00 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T09:45:00Z',
    assignedDriverId: 'DRV-BLR-09',
  },
  {
    id: 'DEL-1003',
    trackingNumber: 'SBT-BLR-882192',
    customer: {
      id: 'CUST-403',
      name: 'Sneha Kulkarni',
      phone: '+91 99001 44521',
    },
    address: {
      street: 'Green Glen Layout, Bellandur',
      unitOrFlat: 'B-301, Ferns Paradise',
      landmark: 'Opposite Shell Petrol Pump',
      city: 'Bengaluru',
      postalCode: '560103',
      latitude: 12.9298,
      longitude: 77.6743,
      residenceCategory: 'apartment',
    },
    packageDescription: 'Kitchenware — Espresso Machine',
    estimatedDeliveryWindow: '01:30 PM - 02:30 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T10:00:00Z',
    assignedDriverId: 'DRV-BLR-09',
  },
  {
    id: 'DEL-1004',
    trackingNumber: 'SBT-BLR-882193',
    customer: {
      id: 'CUST-404',
      name: 'Manoj Hegde',
      phone: '+91 98860 33119',
    },
    address: {
      street: '14th Main, 7th Sector, HSR Layout',
      unitOrFlat: 'Villa 12, Prestige Ferns',
      landmark: 'Near BDA Complex',
      city: 'Bengaluru',
      postalCode: '560102',
      latitude: 12.9116,
      longitude: 77.6389,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Medicine / Perishables — Cold Storage Pack',
    estimatedDeliveryWindow: '03:00 PM - 04:00 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T10:15:00Z',
    assignedDriverId: 'DRV-BLR-09',
  },
  {
    id: 'DEL-1005',
    trackingNumber: 'SBT-BLR-882194',
    customer: {
      id: 'CUST-405',
      name: 'Priya Nambiar',
      phone: '+91 98452 33190',
    },
    address: {
      street: 'Prestige Falcon City, Kanakapura Road',
      unitOrFlat: 'B-1402',
      landmark: 'Near Metro Station',
      city: 'Bengaluru',
      postalCode: '560062',
      latitude: 12.8912,
      longitude: 77.5621,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Electronics — Apple iPad Air M2 & Apple Pencil',
    estimatedDeliveryWindow: '04:00 PM - 05:00 PM',
    status: 'IN_TRANSIT',
    createdAt: '2026-09-18T10:30:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Requires doorstep delivery; Resident ID verification at lobby.',
  },
  {
    id: 'DEL-1006',
    trackingNumber: 'SBT-BLR-882195',
    customer: {
      id: 'CUST-406',
      name: 'Arvind Swaminathan',
      phone: '+91 98801 77241',
    },
    address: {
      street: 'RMZ Ecospace, Outer Ring Road, Bellandur',
      unitOrFlat: 'Bay 4, 3rd Floor',
      landmark: 'Building 2A',
      city: 'Bengaluru',
      postalCode: '560103',
      latitude: 12.9260,
      longitude: 77.6830,
      residenceCategory: 'apartment',
    },
    packageDescription: 'Corporate Handoff — Urgent Signed Legal Documents',
    estimatedDeliveryWindow: '05:15 PM - 06:00 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T10:45:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Corporate legal documents — security desk drop allowed.',
  },
  {
    id: 'DEL-1007',
    trackingNumber: 'SBT-BLR-882196',
    customer: {
      id: 'CUST-407',
      name: 'Ananya Deshmukh',
      phone: '+91 97310 99420',
    },
    address: {
      street: '7th Cross, 4th Block, Koramangala',
      unitOrFlat: '#88',
      landmark: 'Near Maharaja Signal',
      city: 'Bengaluru',
      postalCode: '560034',
      latitude: 12.9344,
      longitude: 77.6258,
      residenceCategory: 'individual_house',
    },
    packageDescription: 'Perishables — Temperature Sensitive Biological Sample Pack',
    estimatedDeliveryWindow: '06:15 PM - 07:00 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T11:00:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Keep in insulated container until doorstep handoff.',
  },
  {
    id: 'DEL-1008',
    trackingNumber: 'SBT-BLR-882197',
    customer: {
      id: 'CUST-408',
      name: 'Vikramaditya Roy',
      phone: '+91 96118 22340',
    },
    address: {
      street: 'Brigade Gateway, Dr. Rajkumar Road, Malleshwaram',
      unitOrFlat: 'A-1104',
      landmark: 'Next to Orion Mall',
      city: 'Bengaluru',
      postalCode: '560055',
      latitude: 13.0118,
      longitude: 77.5552,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Luxury Goods — Swiss Chronograph Watch',
    estimatedDeliveryWindow: '07:30 PM - 08:30 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T11:15:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Direct customer handoff mandatory + video verification.',
  },
  {
    id: 'DEL-1009',
    trackingNumber: 'SBT-BLR-882198',
    customer: { id: 'CUST-409', name: 'Rohan Sen', phone: '+91 98450 11992' },
    address: {
      street: 'Prestige Shantiniketan, ITPL Main Road, Whitefield',
      unitOrFlat: 'Tower 16, Flat 1201',
      landmark: 'Opposite Manipal Hospital',
      city: 'Bengaluru',
      postalCode: '560066',
      latitude: 12.9892,
      longitude: 77.7281,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Computing — MacBook Pro M3 MagSafe Charger & Thunderbolt Hub',
    estimatedDeliveryWindow: '09:00 AM - 10:00 AM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T11:30:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Call on arrival for visitor gate entry passcode.',
  },
  {
    id: 'DEL-1010',
    trackingNumber: 'SBT-BLR-882199',
    customer: { id: 'CUST-410', name: 'Meera Iyer', phone: '+91 97401 22883' },
    address: {
      street: '100 Feet Road, HAL 2nd Stage, Indiranagar',
      unitOrFlat: 'Penthouse 4B',
      landmark: 'Near Toit Brewpub',
      city: 'Bengaluru',
      postalCode: '560038',
      latitude: 12.9734,
      longitude: 77.6402,
      residenceCategory: 'apartment',
    },
    packageDescription: 'Personal Care — Dyson Airwrap Multi-Styler',
    estimatedDeliveryWindow: '10:15 AM - 11:00 AM',
    status: 'IN_TRANSIT',
    createdAt: '2026-09-18T11:45:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Deliver to 4th floor doorstep; elevator functional.',
  },
  {
    id: 'DEL-1011',
    trackingNumber: 'SBT-BLR-882200',
    customer: { id: 'CUST-411', name: 'Karthik Reddy', phone: '+91 99802 33774' },
    address: {
      street: '27th Main, Sector 1, HSR Layout',
      unitOrFlat: '#128',
      landmark: 'Near NIFT Campus',
      city: 'Bengaluru',
      postalCode: '560102',
      latitude: 12.9152,
      longitude: 77.6514,
      residenceCategory: 'individual_house',
    },
    packageDescription: 'Gourmet — Nespresso Coffee Pods & Glass Decanter Set',
    estimatedDeliveryWindow: '11:15 AM - 12:00 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T12:00:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Ring doorbell twice; leave on porch if no response.',
  },
  {
    id: 'DEL-1012',
    trackingNumber: 'SBT-BLR-882201',
    customer: { id: 'CUST-412', name: 'Deepa Balakrishnan', phone: '+91 98863 44665' },
    address: {
      street: 'Salarpuria Sattva Greenage, Hosur Road, Bommanahalli',
      unitOrFlat: 'Alpine Tower, Flat 804',
      landmark: 'Near Oxford College',
      city: 'Bengaluru',
      postalCode: '560068',
      latitude: 12.9022,
      longitude: 77.6254,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Farm Produce — Fresh Organic Artisanal Dairy Basket',
    estimatedDeliveryWindow: '12:30 PM - 01:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T12:15:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Perishable item; keep chilled.',
  },
  {
    id: 'DEL-1013',
    trackingNumber: 'SBT-BLR-882202',
    customer: { id: 'CUST-413', name: 'Aditya Singhania', phone: '+91 99014 55886' },
    address: {
      street: 'Lavelle Road, Shanthala Nagar, Ashok Nagar',
      unitOrFlat: 'Suite 302, Regency Heights',
      landmark: 'Near Bangalore Club',
      city: 'Bengaluru',
      postalCode: '560001',
      latitude: 12.9716,
      longitude: 77.5946,
      residenceCategory: 'apartment',
    },
    packageDescription: 'Stationery — Montblanc Meisterstück Fountain Pen Gold Coated',
    estimatedDeliveryWindow: '01:30 PM - 02:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T12:30:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'High value insured package; signature and video required.',
  },
  {
    id: 'DEL-1014',
    trackingNumber: 'SBT-BLR-882203',
    customer: { id: 'CUST-414', name: 'Shreya Joshi', phone: '+91 97425 66997' },
    address: {
      street: '33rd Cross, 11th Main, 4th T Block, Jayanagar',
      unitOrFlat: '#412',
      landmark: 'Near Jayanagar Shopping Complex',
      city: 'Bengaluru',
      postalCode: '560041',
      latitude: 12.9254,
      longitude: 77.5938,
      residenceCategory: 'individual_house',
    },
    packageDescription: 'Handicrafts — Handcrafted Kashmiri Walnut Wood Keepsake Box',
    estimatedDeliveryWindow: '02:30 PM - 03:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T12:45:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Fragile handling mandatory.',
  },
  {
    id: 'DEL-1015',
    trackingNumber: 'SBT-BLR-882204',
    customer: { id: 'CUST-415', name: 'Farhan Akhtar', phone: '+91 98806 77118' },
    address: {
      street: 'Embassy GolfLinks, Intermediate Ring Road, Domlur',
      unitOrFlat: 'Pebble Beach Block B, 2nd Floor',
      landmark: 'Behind Dell Campus',
      city: 'Bengaluru',
      postalCode: '560071',
      latitude: 12.9515,
      longitude: 77.6482,
      residenceCategory: 'apartment',
    },
    packageDescription: 'Audio Gear — Bose QuietComfort Ultra Wireless Noise-Cancelling Earbuds',
    estimatedDeliveryWindow: '03:30 PM - 04:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T13:00:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Corporate park entry; show driver badge at security post.',
  },
  {
    id: 'DEL-1016',
    trackingNumber: 'SBT-BLR-882205',
    customer: { id: 'CUST-416', name: 'Tanvi Madhavan', phone: '+91 96117 88229' },
    address: {
      street: 'Godrej Platinum, Bellary Road, Hebbal',
      unitOrFlat: 'Tower B, Flat 1803',
      landmark: 'Near Esteem Mall',
      city: 'Bengaluru',
      postalCode: '560024',
      latitude: 13.0358,
      longitude: 77.5970,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Hardware — ASUS ROG GeForce RTX 4080 Super OC Edition',
    estimatedDeliveryWindow: '04:30 PM - 05:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T13:15:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Fragile electronic equipment; do not tilt box.',
  },
  {
    id: 'DEL-1017',
    trackingNumber: 'SBT-BLR-882206',
    customer: { id: 'CUST-417', name: 'Nikhil Kamath', phone: '+91 98458 99330' },
    address: {
      street: 'Sankey Road, Sadashivanagar',
      unitOrFlat: '#19',
      landmark: 'Opposite Sankey Tank Park',
      city: 'Bengaluru',
      postalCode: '560080',
      latitude: 13.0068,
      longitude: 77.5813,
      residenceCategory: 'individual_house',
    },
    packageDescription: 'Banking Courier — Tamper-Evident Physical Ledger Hardware Key',
    estimatedDeliveryWindow: '05:30 PM - 06:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T13:30:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Strict zero-trust delivery: biometric OTP handoff only.',
  },
  {
    id: 'DEL-1018',
    trackingNumber: 'SBT-BLR-882207',
    customer: { id: 'CUST-418', name: 'Pooja Sundaram', phone: '+91 99029 00441' },
    address: {
      street: 'Phoenix One Bangalore West, Dr. Rajkumar Road, Rajajinagar',
      unitOrFlat: 'Tower 4, Flat 2202',
      landmark: 'Opposite ISKCON Temple',
      city: 'Bengaluru',
      postalCode: '560010',
      latitude: 13.0102,
      longitude: 77.5518,
      residenceCategory: 'gated_society',
    },
    packageDescription: 'Luxury Apparel — Louis Vuitton Speedy Bandoulière Monogram Bag',
    estimatedDeliveryWindow: '06:30 PM - 07:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T13:45:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Resident requested video footage handoff confirmation.',
  },
  {
    id: 'DEL-1019',
    trackingNumber: 'SBT-BLR-882208',
    customer: { id: 'CUST-419', name: 'Varun Grover', phone: '+91 97430 11552' },
    address: {
      street: '80 Feet Road, 6th Block, Koramangala',
      unitOrFlat: 'Apartment 201, Green Leaf',
      landmark: 'Near Sony World Signal',
      city: 'Bengaluru',
      postalCode: '560095',
      latitude: 12.9372,
      longitude: 77.6271,
      residenceCategory: 'apartment',
    },
    packageDescription: 'Wellness — Wakefit Orthopedic Memory Foam Support Mattress',
    estimatedDeliveryWindow: '07:30 PM - 08:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T14:00:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'Heavy parcel; doorstep assistance requested.',
  },
  {
    id: 'DEL-1020',
    trackingNumber: 'SBT-BLR-882209',
    customer: { id: 'CUST-420', name: 'Ayesha Siddiqui', phone: '+91 98861 22663' },
    address: {
      street: 'Cunningham Road, Vasanth Nagar',
      unitOrFlat: '#45',
      landmark: 'Near Fatima Bakery',
      city: 'Bengaluru',
      postalCode: '560052',
      latitude: 12.9866,
      longitude: 77.5968,
      residenceCategory: 'individual_house',
    },
    packageDescription: 'Heirloom Jewelry — Antique Gold Filigree Appraisal Box',
    estimatedDeliveryWindow: '08:30 PM - 09:15 PM',
    status: 'ASSIGNED',
    createdAt: '2026-09-18T14:15:00Z',
    assignedDriverId: 'DRV-BLR-09',
    notes: 'High security parcel; mandatory tamper check before handoff.',
  },
];

export const DEMO_SCENARIO_PRESETS: DemoScenarioPreset[] = [
  {
    id: 'SCENARIO_A',
    title: 'Scenario A: Genuine Attempt (Gated Society)',
    subtitle: 'Inside 50m geofence, 158s dwell, call completed, video consent approved',
    tag: 'Genuine Attempt',
    expectedDecision: 'VERIFIED',
    targetDeliveryId: 'DEL-1001',
    simulatedGps: {
      latitude: 12.8717, // ~38m from destination
      longitude: 77.6536,
      accuracy: 6,
      distanceMeters: 38,
    },
    dwellSeconds: 158, // exceeds 150s requirement for gated society
    callAttempted: true,
    callDurationSeconds: 24,
    videoConsentStatus: 'granted',
    anomalyFlags: [],
    description: 'Driver navigated to Sobha Silicon Oasis, waited 158s at the gate/door, called the customer for 24s, and obtained consented video evidence.',
  },
  {
    id: 'SCENARIO_B',
    title: 'Scenario B: Insufficient Attempt (Drive-By / Remote)',
    subtitle: '3.2km away from address, 8s dwell, no phone call made',
    tag: 'Falsified Claim',
    expectedDecision: 'REJECTED',
    targetDeliveryId: 'DEL-1001',
    simulatedGps: {
      latitude: 12.9000, // 3.2km away
      longitude: 77.6534,
      accuracy: 8,
      distanceMeters: 3200,
    },
    dwellSeconds: 8,
    callAttempted: false,
    callDurationSeconds: 0,
    videoConsentStatus: 'not_requested',
    anomalyFlags: ['DISTANCE_EXCEEDED', 'INSUFFICIENT_DWELL', 'NO_CALL_ATTEMPTED'],
    description: 'Driver claimed customer was unavailable while still 3.2km away, with only 8s of recorded dwell and zero call attempts.',
  },
  {
    id: 'SCENARIO_C',
    title: 'Scenario C: Ambiguous Telemetry / Poor GPS',
    subtitle: 'Degraded GPS accuracy (68m uncertainty), inconclusive call duration',
    tag: 'Borderline Evidence',
    expectedDecision: 'REVIEW',
    targetDeliveryId: 'DEL-1001',
    simulatedGps: {
      latitude: 12.8719,
      longitude: 77.6538,
      accuracy: 68, // very poor accuracy
      distanceMeters: 45,
    },
    dwellSeconds: 152,
    callAttempted: true,
    callDurationSeconds: 3, // very short ring
    videoConsentStatus: 'not_requested',
    anomalyFlags: ['POOR_GPS_ACCURACY_UNCERTAINTY', 'SHORT_CALL_DURATION'],
    description: 'Driver was near destination, but GPS horizontal uncertainty was 68m and the call disconnected after 3 seconds. Sent to Ops review.',
  },
  {
    id: 'SCENARIO_D',
    title: 'Scenario D: Sub-Threshold Dwell & Consent Timeout',
    subtitle: '48m distance, 110s/150s dwell, consent timed out without response',
    tag: 'Dwell Gap',
    expectedDecision: 'REVIEW',
    targetDeliveryId: 'DEL-1001',
    simulatedGps: {
      latitude: 12.8718,
      longitude: 77.6535,
      accuracy: 10,
      distanceMeters: 48,
    },
    dwellSeconds: 110, // 110s is < 150s required for gated society
    callAttempted: true,
    callDurationSeconds: 18,
    videoConsentStatus: 'timed_out',
    anomalyFlags: ['SUB_THRESHOLD_DWELL_TIME', 'VIDEO_CONSENT_TIMEOUT'],
    description: 'Driver left after 110s (below the 150s gated society requirement) and the customer video consent link timed out.',
  },
];
